export default {
  carriers: {
    1: 'Cargus',
    2: 'DPD',
    3: 'FanCourier',
    4: 'GLS',
    5: 'Nemo',
    6: 'Sameday',
    7: 'ExpressOne',
    8: 'Econt',
    9: 'TeamCourier',
    10: 'DHL',
    11: 'Posta Romana',
    12: 'Posta Panduri',
    13: 'GLS Hungary',
    14: 'DragonStar',
    15: 'Coletaria',
    16: 'Bookurier',
    17: 'Asendia',
    18: 'TNT',
    19: 'Speedy Bulgaria',
    20: 'GLS Croatia',
    21: 'GLS Czech Republic',
    22: 'GLS Slovenia',
    23: 'GLS Slovakia',
    24: 'InOut',
    25: 'Stack Courier',
    26: 'Gebruder Weiss',
    27: 'Pallex',
    28: 'Geniki Taxydromiki',
    29: 'Courier Manager',
    30: 'GLS Italy',
    31: 'ECourier',
    32: 'Unimasters',
    33: 'TCE',
    34: 'Transilvania Post',
    35: 'Evropat Bulgaria',
    36: 'Bulgarian Post',
    37: 'SMP Courier',
    38: 'DHL Germany',
    39: 'Raben',
    40: 'Memex',
    41: 'PTT Express',
    42: 'XD Courier',
    43: 'Intelligent Logistik',
  },
  constants: {
    price_multiplier: 100,
    invoiced: 'invoiced',
    handling: 'handling',
    shipping: 'Shipping',
    auto: 'auto',
    promissory: 'promissory',
    ready_for_handling: 'ready-for-handling',
    window_to_cancel: 'window-to-cancel',
    pickup: 'pickup',
  },
}
